#! /bin/bash
#-------------------------------------------------------------------------------
# Copyright 2018 Schuyler Eldridge
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# Acts as a front-end for storing daily notes.

# The editor to use
editor=$EDITOR

# Query `date` to get the year, month, and day. This has a built in
# offset to try and keep things grouped by working days.
HOUR_OFFSET=-4
YEAR=`date -d "$HOUR_OFFSET hour" +%Y`
MONTH=`date -d "$HOUR_OFFSET hour" +%m`
DAY=`date -d "$HOUR_OFFSET hour" +%d`
WHOAMI=`whoami`
# Figure out what directory this script is in
DIR=$( cd "$( readlink -f "${BASH_SOURCE[0]}" | xargs dirname )" && \
             pwd | sed 's/\/scripts$//' )
DIR_SRC=$DIR/src/captains-log

echo "Today is $YEAR-$MONTH-$DAY in $DIR"

# Setup the files that we care about
DIR_LOG=$DIR_SRC/$YEAR/$YEAR-$MONTH
LOG=$DIR_LOG/$YEAR-$MONTH-$DAY.md

# If the files don't exist, then create them
if [ ! -e $LOG ]; then
    mkdir -p $DIR_LOG
    touch $LOG
    echo "# $YEAR.$MONTH.$DAY | $WHOAMI" > $LOG
fi
$editor $LOG

# Take the 30 most recent entries and put them into a file called
# recent.md increasing every header that we see by one.
echo "# Captain's Log " > $DIR_SRC/recent.md
echo "--------------------" >> $DIR_SRC/recent.md
echo "Recent Entries" >> $DIR_SRC/recent.md
find $DIR_SRC/*/ | \
    grep md$ | \
    sort -nr | \
    head -n 30 | \
    xargs -n 1 sed -e 's/^#/##/' -e '$a\\' >> $DIR_SRC/recent.md

# Rebuild the log
make -C $DIR
