#! /bin/bash
#-------------------------------------------------------------------------------
# Copyright 2018 Schuyler Eldridge
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# Tries to find one of the following markdown interpreters in your
# PATH. Otherwise, will fail.
#   * `gfm` -- Github-Flavored Markdown
#   * `markdown` -- Daring Fireball Markdown

if [[ $# -ne 1 ]]; then
    echo "Usage:"
    echo "  ./markdown-chooser [input file]"
    exit 1
fi

if [[ -n `which pandoc 2> /dev/null` ]]; then
    pandoc $1
elif [[ -n `which marked 2> /dev/null` ]]; then
    marked $1
elif [[ -n `which markdown 2> /dev/null` ]]; then
    markdown $1
else
    echo "Cannot find a suitable Markdown parser on your Path!"
    exit 1
fi
