#!/usr/bin/perl
#-------------------------------------------------------------------------------
# Copyright 2018 Schuyler Eldridge
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;
use warnings;

sub usage() {
    print "Usage: scrub-pygmentize FILE\n";
}

if ($#ARGV != 0) {
    usage() and die "Bad input arguments";
}

open(FILE, "<", $ARGV[0]) or die "Unable to open $ARGV[0]";

my $in_code_block = 0;
my $language = "";
my $code_block;
while (<FILE>) {
    if ($_ =~ /``` ?(\w*)?/ and not $in_code_block) {
        $in_code_block = 1;
        $language = $1;
        $code_block = "";
        next;
    }
    elsif ($_ =~ /```/) {
        $in_code_block = 0;

        my $language_arg = ($language) ? "-l $language" : "";
        my @args = ("echo \"$code_block\" | pygmentize -f html $language_arg");
        system(@args) == 0 or die "Bad system call";

        next;
    }
    elsif (not $in_code_block) {
        print $_;
        next;
    }

    $code_block = $code_block.$_;
}

close FILE;
